Fix compiler build and example datamodel code

diff --git a/nexus/compiler/Dockerfile b/nexus/compiler/Dockerfile
--- a/nexus/compiler/Dockerfile
+++ b/nexus/compiler/Dockerfile
@@ -11,6 +11,7 @@ ENV GOCACHE=/home/appuser/.cache/go-build
 
 # Copy sources and binaries with correct ownership.
 ADD --chown=appuser:appuser compiler.tar /go/src/github.com/vmware-tanzu/graph-framework-for-microservices/compiler
+
 COPY --chown=appuser:appuser cmd/nexus-openapi-gen /go/bin/nexus-openapi-gen
 COPY --chown=appuser:appuser cmd/gqlgen /go/bin/gqlgen
 
@@ -23,8 +24,9 @@ WORKDIR /go/src/github.com/vmware-tanzu/graph-framework-for-microservices/compil
 RUN mv .git kube-openapi gqlgen nexus install-validator common-library ..
 USER appuser
 
-RUN git config --global --add safe.directory '*' \
- && git config --global --add url."https://github.com/".insteadOf "git@github.com:"
+# Ignore errors if git config fails; for cases where compiler repo is imported as git submodule.
+RUN (git config --global --add safe.directory '*' || true) && \
+    (git config --global --add url."https://github.com/".insteadOf "git@github.com:" || true)
 
 RUN make init_submodules
 
@@ -47,5 +49,11 @@ USER appuser
 
 WORKDIR /go/src/github.com/vmware-tanzu/graph-framework-for-microservices/compiler
 RUN --mount=type=cache,target="/home/appuser/.cache/go-build" go mod download || go mod download
+
+USER root
+RUN chmod -R o+w /go/src/github.com/vmware-tanzu/graph-framework-for-microservices/compiler
+RUN chmod -R o+w /go/pkg
+RUN chmod -R o+w /home/appuser
+USER appuser
 
 CMD ["make", "preparser"]
